close all
clc

hold on
plot(Time,Speed) % uses workspace variables generated by simulink simulation
ylim([40 52])% Y axis limits
xlim([0 100])% X axis limits
ylabel('Speed (mi/h)')
xlabel('Time (s)')
title('Response vs Time')
desired = refline([0 50]); % dashed line at desired value of 50MPH for reference
set(desired,'LineStyle',':') % styling for reference line
error = abs(50-Speed)/50; % calculates error for each member in speed array
index = find(error<0.01,1); % gets index of first error element that is within to 0.01
time = Time(index); % gets time value for first element that is within to 0.01
plot(time,Speed(index),'b*')
firstB = line([62.5,62.5],[40,49.5]);
lastB = line([78,78],[40,49.5]);
set(firstB,'LineStyle',':','color','r')
set(lastB,'LineStyle',':','color','r')


legend('Output', 'Desired','Ts = 10.2646 secs')
disp(['Time when error is within 1%: ' num2str(time) ' secs'])
grid on % gridlines for reference